### PR TITLE
Travis CI, Drop Node Version

### PR DESCRIPTION
**Pull request by rjhilgefort**
- Adding CI
- Loosening Node Version
- Drop yarn req so user can use whatever version

---

@spacetc62 As an outside collab, I cannot activate the repo in travis to test this config. Before merging this, would you enable this repo in Travis and let me know so I can validate?

### CODE REVIEW

**Comment by spacetc62** [comment]
@rjhilgefort added it https://travis-ci.org/Losant/omnibelt - it isn't seeing this PR yet, though, for some reason

**Comment by rjhilgefort** [comment]
@spacetc62 I didn't see a manual kick off button in Travis. Looks like doing a commit to bump the CI worked to kick it off. Thanks for adding to Travis.

**Comment by rjhilgefort** [comment]
I don't think I'm a collaborator on that project, so that would be great. I don't mean to create tasks for you with this PR, so if you make me an outside collaborator, I'm happy to make the update as well.

**Comment by spacetc62** [comment]
all passing now, merging!

**Pull request merged**
